const MONGODB = {
    url: 'mongodb://127.0.0.1:27017/blog_data'
}

// token有效时长 单位S（秒）
const TOKEN_VAILD = {
    TIME: 3600
}

const RESPONSE_CODE = {
    RESPONSE_CODE_OK: 200,
    RESPONSE_CODE_BAD_REQUEST: 400,
    RESPONSE_CODE_NO_ACCESS: 401,
    RESPONSE_CODE_NO_PERMISSION: 403,
    RESPONSE_CODE_NOT_FOUND: 404,
    RESPONSE_CODE_SERVER_ERROR: 500
}
module.exports = {
    MONGODB,
    RESPONSE_CODE,
    TOKEN_VAILD
}
